# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyconfig_gen_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(543, 644)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainDialog.sizePolicy().hasHeightForWidth())
        MainDialog.setSizePolicy(sizePolicy)
        MainDialog.setMinimumSize(QtCore.QSize(0, 0))
        MainDialog.setBaseSize(QtCore.QSize(0, 10))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/main_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainDialog.setWindowIcon(icon)
        MainDialog.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(MainDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.main_bb = QtWidgets.QDialogButtonBox(MainDialog)
        self.main_bb.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.main_bb.setObjectName("main_bb")
        self.gridLayout.addWidget(self.main_bb, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(MainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.display_tab = QtWidgets.QWidget()
        self.display_tab.setObjectName("display_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.display_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphics_driver_gb = QtWidgets.QHBoxLayout()
        self.graphics_driver_gb.setObjectName("graphics_driver_gb")
        self.graphics_driver_lb = QtWidgets.QLabel(self.display_tab)
        self.graphics_driver_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.graphics_driver_lb.setObjectName("graphics_driver_lb")
        self.graphics_driver_gb.addWidget(self.graphics_driver_lb)
        self.graphics_driver_cb = QtWidgets.QComboBox(self.display_tab)
        self.graphics_driver_cb.setToolTip("")
        self.graphics_driver_cb.setStatusTip("")
        self.graphics_driver_cb.setObjectName("graphics_driver_cb")
        self.graphics_driver_cb.addItem("")
        self.graphics_driver_cb.addItem("")
        self.graphics_driver_cb.addItem("")
        self.graphics_driver_gb.addWidget(self.graphics_driver_cb)
        self.cma_lb = QtWidgets.QLabel(self.display_tab)
        self.cma_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cma_lb.setObjectName("cma_lb")
        self.graphics_driver_gb.addWidget(self.cma_lb)
        self.cma_cb = QtWidgets.QComboBox(self.display_tab)
        self.cma_cb.setObjectName("cma_cb")
        self.cma_cb.addItem("")
        self.cma_cb.addItem("")
        self.cma_cb.addItem("")
        self.cma_cb.addItem("")
        self.cma_cb.addItem("")
        self.cma_cb.addItem("")
        self.graphics_driver_gb.addWidget(self.cma_cb)
        self.gpu_lb = QtWidgets.QLabel(self.display_tab)
        self.gpu_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gpu_lb.setObjectName("gpu_lb")
        self.graphics_driver_gb.addWidget(self.gpu_lb)
        self.gpu_cb = QtWidgets.QComboBox(self.display_tab)
        self.gpu_cb.setObjectName("gpu_cb")
        self.gpu_cb.addItem("")
        self.gpu_cb.addItem("")
        self.gpu_cb.addItem("")
        self.gpu_cb.addItem("")
        self.gpu_cb.addItem("")
        self.gpu_cb.addItem("")
        self.gpu_cb.addItem("")
        self.gpu_cb.addItem("")
        self.graphics_driver_gb.addWidget(self.gpu_cb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.graphics_driver_gb.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.graphics_driver_gb)
        self.mode_gb = QtWidgets.QHBoxLayout()
        self.mode_gb.setObjectName("mode_gb")
        self.normal_mode_rb = QtWidgets.QRadioButton(self.display_tab)
        self.normal_mode_rb.setChecked(False)
        self.normal_mode_rb.setObjectName("normal_mode_rb")
        self.mode_gb.addWidget(self.normal_mode_rb)
        self.safe_mode_rb = QtWidgets.QRadioButton(self.display_tab)
        self.safe_mode_rb.setChecked(True)
        self.safe_mode_rb.setObjectName("safe_mode_rb")
        self.mode_gb.addWidget(self.safe_mode_rb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.mode_gb.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.mode_gb)
        self.normal_mode_gb = QtWidgets.QGroupBox(self.display_tab)
        self.normal_mode_gb.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normal_mode_gb.sizePolicy().hasHeightForWidth())
        self.normal_mode_gb.setSizePolicy(sizePolicy)
        self.normal_mode_gb.setMinimumSize(QtCore.QSize(0, 0))
        self.normal_mode_gb.setObjectName("normal_mode_gb")
        self.formLayout = QtWidgets.QFormLayout(self.normal_mode_gb)
        self.formLayout.setObjectName("formLayout")
        self.hdmi_group_lb = QtWidgets.QLabel(self.normal_mode_gb)
        self.hdmi_group_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hdmi_group_lb.setObjectName("hdmi_group_lb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.hdmi_group_lb)
        self.hdmi_group_cb = QtWidgets.QComboBox(self.normal_mode_gb)
        self.hdmi_group_cb.setObjectName("hdmi_group_cb")
        self.hdmi_group_cb.addItem("")
        self.hdmi_group_cb.addItem("")
        self.hdmi_group_cb.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hdmi_group_cb)
        self.hdmi_mode_lb = QtWidgets.QLabel(self.normal_mode_gb)
        self.hdmi_mode_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hdmi_mode_lb.setObjectName("hdmi_mode_lb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.hdmi_mode_lb)
        self.hdmi_mode_cb = QtWidgets.QComboBox(self.normal_mode_gb)
        self.hdmi_mode_cb.setObjectName("hdmi_mode_cb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hdmi_mode_cb)
        self.additional_opts_gb = QtWidgets.QGroupBox(self.normal_mode_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.additional_opts_gb.sizePolicy().hasHeightForWidth())
        self.additional_opts_gb.setSizePolicy(sizePolicy)
        self.additional_opts_gb.setMinimumSize(QtCore.QSize(200, 180))
        self.additional_opts_gb.setCheckable(False)
        self.additional_opts_gb.setObjectName("additional_opts_gb")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.additional_opts_gb)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hdmi_force_hotplug_cb = QtWidgets.QCheckBox(self.additional_opts_gb)
        self.hdmi_force_hotplug_cb.setObjectName("hdmi_force_hotplug_cb")
        self.verticalLayout_2.addWidget(self.hdmi_force_hotplug_cb)
        self.hdmi_ignore_edid_cb = QtWidgets.QCheckBox(self.additional_opts_gb)
        self.hdmi_ignore_edid_cb.setObjectName("hdmi_ignore_edid_cb")
        self.verticalLayout_2.addWidget(self.hdmi_ignore_edid_cb)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.config_hdmi_boost_lb = QtWidgets.QLabel(self.additional_opts_gb)
        self.config_hdmi_boost_lb.setObjectName("config_hdmi_boost_lb")
        self.horizontalLayout_3.addWidget(self.config_hdmi_boost_lb)
        self.config_hdmi_boost_sb = QtWidgets.QSpinBox(self.additional_opts_gb)
        self.config_hdmi_boost_sb.setMaximum(11)
        self.config_hdmi_boost_sb.setProperty("value", 5)
        self.config_hdmi_boost_sb.setObjectName("config_hdmi_boost_sb")
        self.horizontalLayout_3.addWidget(self.config_hdmi_boost_sb)
        self.config_hdmi_boost_status_lb = QtWidgets.QLabel(self.additional_opts_gb)
        self.config_hdmi_boost_status_lb.setText("")
        self.config_hdmi_boost_status_lb.setObjectName("config_hdmi_boost_status_lb")
        self.horizontalLayout_3.addWidget(self.config_hdmi_boost_status_lb)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.overscan_gb = QtWidgets.QGroupBox(self.additional_opts_gb)
        self.overscan_gb.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overscan_gb.sizePolicy().hasHeightForWidth())
        self.overscan_gb.setSizePolicy(sizePolicy)
        self.overscan_gb.setCheckable(True)
        self.overscan_gb.setChecked(False)
        self.overscan_gb.setObjectName("overscan_gb")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.overscan_gb)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.overscan_left_lb = QtWidgets.QLabel(self.overscan_gb)
        self.overscan_left_lb.setObjectName("overscan_left_lb")
        self.horizontalLayout_4.addWidget(self.overscan_left_lb)
        self.overscan_left_sb = QtWidgets.QSpinBox(self.overscan_gb)
        self.overscan_left_sb.setProperty("value", 24)
        self.overscan_left_sb.setObjectName("overscan_left_sb")
        self.horizontalLayout_4.addWidget(self.overscan_left_sb)
        self.overscan_right_lb = QtWidgets.QLabel(self.overscan_gb)
        self.overscan_right_lb.setObjectName("overscan_right_lb")
        self.horizontalLayout_4.addWidget(self.overscan_right_lb)
        self.overscan_right_sb = QtWidgets.QSpinBox(self.overscan_gb)
        self.overscan_right_sb.setProperty("value", 24)
        self.overscan_right_sb.setObjectName("overscan_right_sb")
        self.horizontalLayout_4.addWidget(self.overscan_right_sb)
        self.overscan_top_lb = QtWidgets.QLabel(self.overscan_gb)
        self.overscan_top_lb.setObjectName("overscan_top_lb")
        self.horizontalLayout_4.addWidget(self.overscan_top_lb)
        self.overscan_top_sb = QtWidgets.QSpinBox(self.overscan_gb)
        self.overscan_top_sb.setProperty("value", 24)
        self.overscan_top_sb.setObjectName("overscan_top_sb")
        self.horizontalLayout_4.addWidget(self.overscan_top_sb)
        self.overscan_bottom_lb = QtWidgets.QLabel(self.overscan_gb)
        self.overscan_bottom_lb.setObjectName("overscan_bottom_lb")
        self.horizontalLayout_4.addWidget(self.overscan_bottom_lb)
        self.overscan_bottom_sb = QtWidgets.QSpinBox(self.overscan_gb)
        self.overscan_bottom_sb.setProperty("value", 24)
        self.overscan_bottom_sb.setObjectName("overscan_bottom_sb")
        self.horizontalLayout_4.addWidget(self.overscan_bottom_sb)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.overscan_gb)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.additional_opts_gb)
        self.verticalLayout_4.addWidget(self.normal_mode_gb)
        self.further_settings_gb = QtWidgets.QGroupBox(self.display_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.further_settings_gb.sizePolicy().hasHeightForWidth())
        self.further_settings_gb.setSizePolicy(sizePolicy)
        self.further_settings_gb.setMinimumSize(QtCore.QSize(0, 0))
        self.further_settings_gb.setObjectName("further_settings_gb")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.further_settings_gb)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hdmi_drive_cb = QtWidgets.QCheckBox(self.further_settings_gb)
        self.hdmi_drive_cb.setObjectName("hdmi_drive_cb")
        self.verticalLayout_3.addWidget(self.hdmi_drive_cb)
        self.hdmi_force_edid_audio_cb = QtWidgets.QCheckBox(self.further_settings_gb)
        self.hdmi_force_edid_audio_cb.setObjectName("hdmi_force_edid_audio_cb")
        self.verticalLayout_3.addWidget(self.hdmi_force_edid_audio_cb)
        self.verticalLayout_4.addWidget(self.further_settings_gb)
        self.pi4_display_gb = QtWidgets.QGroupBox(self.display_tab)
        self.pi4_display_gb.setObjectName("pi4_display_gb")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pi4_display_gb)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pi4_4kp60_cb = QtWidgets.QCheckBox(self.pi4_display_gb)
        self.pi4_4kp60_cb.setObjectName("pi4_4kp60_cb")
        self.verticalLayout_15.addWidget(self.pi4_4kp60_cb)
        self.verticalLayout_4.addWidget(self.pi4_display_gb)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.tabWidget.addTab(self.display_tab, "")
        self.second_display_tab = QtWidgets.QWidget()
        self.second_display_tab.setObjectName("second_display_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.second_display_tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.hdmi1_gb = QtWidgets.QGroupBox(self.second_display_tab)
        self.hdmi1_gb.setObjectName("hdmi1_gb")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.hdmi1_gb)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mode1_gb = QtWidgets.QHBoxLayout()
        self.mode1_gb.setObjectName("mode1_gb")
        self.normal_mode1_rb = QtWidgets.QRadioButton(self.hdmi1_gb)
        self.normal_mode1_rb.setObjectName("normal_mode1_rb")
        self.mode1_gb.addWidget(self.normal_mode1_rb)
        self.safe_mode1_rb = QtWidgets.QRadioButton(self.hdmi1_gb)
        self.safe_mode1_rb.setChecked(True)
        self.safe_mode1_rb.setObjectName("safe_mode1_rb")
        self.mode1_gb.addWidget(self.safe_mode1_rb)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.mode1_gb.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.mode1_gb)
        self.normal_mode1_gb = QtWidgets.QGroupBox(self.hdmi1_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normal_mode1_gb.sizePolicy().hasHeightForWidth())
        self.normal_mode1_gb.setSizePolicy(sizePolicy)
        self.normal_mode1_gb.setObjectName("normal_mode1_gb")
        self.formLayout_2 = QtWidgets.QFormLayout(self.normal_mode1_gb)
        self.formLayout_2.setObjectName("formLayout_2")
        self.hdmi_group1_cb = QtWidgets.QComboBox(self.normal_mode1_gb)
        self.hdmi_group1_cb.setObjectName("hdmi_group1_cb")
        self.hdmi_group1_cb.addItem("")
        self.hdmi_group1_cb.addItem("")
        self.hdmi_group1_cb.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hdmi_group1_cb)
        self.hdmi_mode1_lb = QtWidgets.QLabel(self.normal_mode1_gb)
        self.hdmi_mode1_lb.setObjectName("hdmi_mode1_lb")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.hdmi_mode1_lb)
        self.hdmi_group1_lb = QtWidgets.QLabel(self.normal_mode1_gb)
        self.hdmi_group1_lb.setObjectName("hdmi_group1_lb")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.hdmi_group1_lb)
        self.hdmi_mode1_cb = QtWidgets.QComboBox(self.normal_mode1_gb)
        self.hdmi_mode1_cb.setObjectName("hdmi_mode1_cb")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hdmi_mode1_cb)
        self.additional_opts1_gb = QtWidgets.QGroupBox(self.normal_mode1_gb)
        self.additional_opts1_gb.setObjectName("additional_opts1_gb")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.additional_opts1_gb)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.hdmi_force_hotplug1_cb = QtWidgets.QCheckBox(self.additional_opts1_gb)
        self.hdmi_force_hotplug1_cb.setObjectName("hdmi_force_hotplug1_cb")
        self.verticalLayout_8.addWidget(self.hdmi_force_hotplug1_cb)
        self.hdmi_ignore_edid1_cb = QtWidgets.QCheckBox(self.additional_opts1_gb)
        self.hdmi_ignore_edid1_cb.setObjectName("hdmi_ignore_edid1_cb")
        self.verticalLayout_8.addWidget(self.hdmi_ignore_edid1_cb)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 4, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.config_hdmi_boost1_lb = QtWidgets.QLabel(self.additional_opts1_gb)
        self.config_hdmi_boost1_lb.setObjectName("config_hdmi_boost1_lb")
        self.horizontalLayout.addWidget(self.config_hdmi_boost1_lb)
        self.config_hdmi_boost1_sb = QtWidgets.QSpinBox(self.additional_opts1_gb)
        self.config_hdmi_boost1_sb.setMaximum(11)
        self.config_hdmi_boost1_sb.setProperty("value", 5)
        self.config_hdmi_boost1_sb.setObjectName("config_hdmi_boost1_sb")
        self.horizontalLayout.addWidget(self.config_hdmi_boost1_sb)
        self.config_hdmi_boost_status1_lb = QtWidgets.QLabel(self.additional_opts1_gb)
        self.config_hdmi_boost_status1_lb.setText("")
        self.config_hdmi_boost_status1_lb.setObjectName("config_hdmi_boost_status1_lb")
        self.horizontalLayout.addWidget(self.config_hdmi_boost_status1_lb)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.additional_opts1_gb)
        self.overscan1_gb = QtWidgets.QGroupBox(self.normal_mode1_gb)
        self.overscan1_gb.setCheckable(True)
        self.overscan1_gb.setChecked(False)
        self.overscan1_gb.setObjectName("overscan1_gb")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.overscan1_gb)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.overscan_left1_lb = QtWidgets.QLabel(self.overscan1_gb)
        self.overscan_left1_lb.setObjectName("overscan_left1_lb")
        self.horizontalLayout_2.addWidget(self.overscan_left1_lb)
        self.overscan_left1_sb = QtWidgets.QSpinBox(self.overscan1_gb)
        self.overscan_left1_sb.setProperty("value", 24)
        self.overscan_left1_sb.setObjectName("overscan_left1_sb")
        self.horizontalLayout_2.addWidget(self.overscan_left1_sb)
        self.overscan_right1_lb = QtWidgets.QLabel(self.overscan1_gb)
        self.overscan_right1_lb.setObjectName("overscan_right1_lb")
        self.horizontalLayout_2.addWidget(self.overscan_right1_lb)
        self.overscan_right1_sb = QtWidgets.QSpinBox(self.overscan1_gb)
        self.overscan_right1_sb.setProperty("value", 24)
        self.overscan_right1_sb.setObjectName("overscan_right1_sb")
        self.horizontalLayout_2.addWidget(self.overscan_right1_sb)
        self.overscan_top1_lb = QtWidgets.QLabel(self.overscan1_gb)
        self.overscan_top1_lb.setObjectName("overscan_top1_lb")
        self.horizontalLayout_2.addWidget(self.overscan_top1_lb)
        self.overscan_top1_sb = QtWidgets.QSpinBox(self.overscan1_gb)
        self.overscan_top1_sb.setProperty("value", 24)
        self.overscan_top1_sb.setObjectName("overscan_top1_sb")
        self.horizontalLayout_2.addWidget(self.overscan_top1_sb)
        self.overscan_bottom1_lb = QtWidgets.QLabel(self.overscan1_gb)
        self.overscan_bottom1_lb.setObjectName("overscan_bottom1_lb")
        self.horizontalLayout_2.addWidget(self.overscan_bottom1_lb)
        self.overscan_bottom1_sb = QtWidgets.QSpinBox(self.overscan1_gb)
        self.overscan_bottom1_sb.setProperty("value", 24)
        self.overscan_bottom1_sb.setObjectName("overscan_bottom1_sb")
        self.horizontalLayout_2.addWidget(self.overscan_bottom1_sb)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.overscan1_gb)
        self.verticalLayout.addWidget(self.normal_mode1_gb)
        self.further_settings2_gb = QtWidgets.QGroupBox(self.hdmi1_gb)
        self.further_settings2_gb.setObjectName("further_settings2_gb")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.further_settings2_gb)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.hdmi_drive1_cb = QtWidgets.QCheckBox(self.further_settings2_gb)
        self.hdmi_drive1_cb.setObjectName("hdmi_drive1_cb")
        self.verticalLayout_9.addWidget(self.hdmi_drive1_cb)
        self.hdmi_force_edid_audio1_cb = QtWidgets.QCheckBox(self.further_settings2_gb)
        self.hdmi_force_edid_audio1_cb.setObjectName("hdmi_force_edid_audio1_cb")
        self.verticalLayout_9.addWidget(self.hdmi_force_edid_audio1_cb)
        self.verticalLayout.addWidget(self.further_settings2_gb)
        self.verticalLayout_7.addWidget(self.hdmi1_gb)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.tabWidget.addTab(self.second_display_tab, "")
        self.wifi_tab = QtWidgets.QWidget()
        self.wifi_tab.setObjectName("wifi_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.wifi_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.main_interfaces_gb = QtWidgets.QGroupBox(self.wifi_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_interfaces_gb.sizePolicy().hasHeightForWidth())
        self.main_interfaces_gb.setSizePolicy(sizePolicy)
        self.main_interfaces_gb.setObjectName("main_interfaces_gb")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.main_interfaces_gb)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.spi_cb = QtWidgets.QCheckBox(self.main_interfaces_gb)
        self.spi_cb.setObjectName("spi_cb")
        self.verticalLayout_6.addWidget(self.spi_cb)
        self.i2c_cb = QtWidgets.QCheckBox(self.main_interfaces_gb)
        self.i2c_cb.setObjectName("i2c_cb")
        self.verticalLayout_6.addWidget(self.i2c_cb)
        self.i2s_cb = QtWidgets.QCheckBox(self.main_interfaces_gb)
        self.i2s_cb.setObjectName("i2s_cb")
        self.verticalLayout_6.addWidget(self.i2s_cb)
        self.bluetooth_cb = QtWidgets.QCheckBox(self.main_interfaces_gb)
        self.bluetooth_cb.setObjectName("bluetooth_cb")
        self.verticalLayout_6.addWidget(self.bluetooth_cb)
        self.audio_cb = QtWidgets.QCheckBox(self.main_interfaces_gb)
        self.audio_cb.setObjectName("audio_cb")
        self.verticalLayout_6.addWidget(self.audio_cb)
        self.camera_cb = QtWidgets.QCheckBox(self.main_interfaces_gb)
        self.camera_cb.setObjectName("camera_cb")
        self.verticalLayout_6.addWidget(self.camera_cb)
        self.verticalLayout_5.addWidget(self.main_interfaces_gb)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.tabWidget.addTab(self.wifi_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.wifi_setup_gb = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wifi_setup_gb.sizePolicy().hasHeightForWidth())
        self.wifi_setup_gb.setSizePolicy(sizePolicy)
        self.wifi_setup_gb.setObjectName("wifi_setup_gb")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.wifi_setup_gb)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.wifi_country_code_lb = QtWidgets.QLabel(self.wifi_setup_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wifi_country_code_lb.sizePolicy().hasHeightForWidth())
        self.wifi_country_code_lb.setSizePolicy(sizePolicy)
        self.wifi_country_code_lb.setObjectName("wifi_country_code_lb")
        self.horizontalLayout_6.addWidget(self.wifi_country_code_lb)
        self.wifi_country_code_cb = QtWidgets.QComboBox(self.wifi_setup_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wifi_country_code_cb.sizePolicy().hasHeightForWidth())
        self.wifi_country_code_cb.setSizePolicy(sizePolicy)
        self.wifi_country_code_cb.setObjectName("wifi_country_code_cb")
        self.horizontalLayout_6.addWidget(self.wifi_country_code_cb)
        self.verticalLayout_12.addWidget(self.wifi_setup_gb)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem10)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.overclocking_gb = QtWidgets.QGroupBox(self.tab)
        self.overclocking_gb.setObjectName("overclocking_gb")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.overclocking_gb)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.overclock0_rb = QtWidgets.QRadioButton(self.overclocking_gb)
        self.overclock0_rb.setChecked(True)
        self.overclock0_rb.setObjectName("overclock0_rb")
        self.verticalLayout_11.addWidget(self.overclock0_rb)
        self.overclock1_rb = QtWidgets.QRadioButton(self.overclocking_gb)
        self.overclock1_rb.setChecked(False)
        self.overclock1_rb.setObjectName("overclock1_rb")
        self.verticalLayout_11.addWidget(self.overclock1_rb)
        self.overclock2_rb = QtWidgets.QRadioButton(self.overclocking_gb)
        self.overclock2_rb.setObjectName("overclock2_rb")
        self.verticalLayout_11.addWidget(self.overclock2_rb)
        self.overclock3_rb = QtWidgets.QRadioButton(self.overclocking_gb)
        self.overclock3_rb.setObjectName("overclock3_rb")
        self.verticalLayout_11.addWidget(self.overclock3_rb)
        self.overclock4_rb = QtWidgets.QRadioButton(self.overclocking_gb)
        self.overclock4_rb.setObjectName("overclock4_rb")
        self.verticalLayout_11.addWidget(self.overclock4_rb)
        self.overclock3_rb.raise_()
        self.overclock1_rb.raise_()
        self.overclock2_rb.raise_()
        self.overclock0_rb.raise_()
        self.overclock4_rb.raise_()
        self.verticalLayout_10.addWidget(self.overclocking_gb)
        self.pimoroni_gb = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pimoroni_gb.sizePolicy().hasHeightForWidth())
        self.pimoroni_gb.setSizePolicy(sizePolicy)
        self.pimoroni_gb.setCheckable(True)
        self.pimoroni_gb.setChecked(False)
        self.pimoroni_gb.setObjectName("pimoroni_gb")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.pimoroni_gb)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.start_fan_lb = QtWidgets.QLabel(self.pimoroni_gb)
        self.start_fan_lb.setObjectName("start_fan_lb")
        self.horizontalLayout_10.addWidget(self.start_fan_lb)
        self.fan_temps_hs = QtWidgets.QSlider(self.pimoroni_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fan_temps_hs.sizePolicy().hasHeightForWidth())
        self.fan_temps_hs.setSizePolicy(sizePolicy)
        self.fan_temps_hs.setMinimumSize(QtCore.QSize(200, 20))
        self.fan_temps_hs.setMinimum(45)
        self.fan_temps_hs.setMaximum(75)
        self.fan_temps_hs.setSingleStep(5)
        self.fan_temps_hs.setProperty("value", 65)
        self.fan_temps_hs.setTracking(True)
        self.fan_temps_hs.setOrientation(QtCore.Qt.Horizontal)
        self.fan_temps_hs.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.fan_temps_hs.setTickInterval(5)
        self.fan_temps_hs.setObjectName("fan_temps_hs")
        self.horizontalLayout_10.addWidget(self.fan_temps_hs)
        self.fan_temps_lb = QtWidgets.QLabel(self.pimoroni_gb)
        self.fan_temps_lb.setObjectName("fan_temps_lb")
        self.horizontalLayout_10.addWidget(self.fan_temps_lb)
        self.verticalLayout_10.addWidget(self.pimoroni_gb)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem11)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.layout_editor_pb = QtWidgets.QPushButton(MainDialog)
        self.layout_editor_pb.setObjectName("layout_editor_pb")
        self.horizontalLayout_7.addWidget(self.layout_editor_pb)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.gridLayout.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)

        self.retranslateUi(MainDialog)
        self.tabWidget.setCurrentIndex(0)
        self.main_bb.accepted.connect(MainDialog.accept)
        self.main_bb.rejected.connect(MainDialog.reject)
        self.main_bb.clicked['QAbstractButton*'].connect(MainDialog.button_bar_button_clicked)
        self.hdmi_force_edid_audio_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.overscan_top_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.graphics_driver_cb.currentIndexChanged['int'].connect(MainDialog.gui_value_changed)
        self.hdmi_group_cb.currentIndexChanged['int'].connect(MainDialog.hdmi_group_changed)
        self.cma_cb.currentIndexChanged['int'].connect(MainDialog.gui_value_changed)
        self.safe_mode_rb.clicked.connect(MainDialog.gui_changed)
        self.normal_mode_rb.clicked.connect(MainDialog.gui_changed)
        self.hdmi_mode_cb.currentIndexChanged['int'].connect(MainDialog.gui_value_changed)
        self.overscan_gb.toggled['bool'].connect(MainDialog.gui_bool_changed)
        self.overscan_right_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.overscan_left_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.config_hdmi_boost_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.hdmi_ignore_edid_cb.stateChanged['int'].connect(MainDialog.hdmi_ignore_edid_changed)
        self.hdmi_force_hotplug_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.overscan_bottom_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.hdmi_drive_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.spi_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.i2c_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.bluetooth_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.i2s_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.audio_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.gpu_cb.currentIndexChanged['int'].connect(MainDialog.gui_value_changed)
        self.camera_cb.stateChanged['int'].connect(MainDialog.camera_cb_value_changed)
        self.normal_mode1_rb.clicked.connect(MainDialog.gui_changed)
        self.safe_mode1_rb.clicked['bool'].connect(MainDialog.gui_changed)
        self.hdmi_group1_cb.currentIndexChanged['int'].connect(MainDialog.hdmi_group1_changed)
        self.hdmi_mode1_cb.currentIndexChanged['int'].connect(MainDialog.gui_value_changed)
        self.hdmi_force_hotplug1_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.hdmi_ignore_edid1_cb.stateChanged['int'].connect(MainDialog.hdmi_ignore_edid1_changed)
        self.config_hdmi_boost1_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.overscan1_gb.toggled['bool'].connect(MainDialog.gui_bool_changed)
        self.overscan_left1_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.overscan_right1_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.overscan_top1_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.overscan_bottom1_sb.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.hdmi_drive1_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.hdmi_force_edid_audio1_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        self.layout_editor_pb.clicked['bool'].connect(MainDialog.layout_editor_button_clicked)
        self.wifi_country_code_cb.currentIndexChanged['int'].connect(MainDialog.gui_value_changed)
        self.pimoroni_gb.toggled['bool'].connect(MainDialog.gui_bool_changed)
        self.fan_temps_hs.valueChanged['int'].connect(MainDialog.gui_value_changed)
        self.pi4_4kp60_cb.stateChanged['int'].connect(MainDialog.gui_value_changed)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)
        MainDialog.setTabOrder(self.graphics_driver_cb, self.cma_cb)
        MainDialog.setTabOrder(self.cma_cb, self.normal_mode_rb)
        MainDialog.setTabOrder(self.normal_mode_rb, self.safe_mode_rb)
        MainDialog.setTabOrder(self.safe_mode_rb, self.hdmi_group_cb)
        MainDialog.setTabOrder(self.hdmi_group_cb, self.hdmi_mode_cb)
        MainDialog.setTabOrder(self.hdmi_mode_cb, self.hdmi_force_hotplug_cb)
        MainDialog.setTabOrder(self.hdmi_force_hotplug_cb, self.hdmi_ignore_edid_cb)
        MainDialog.setTabOrder(self.hdmi_ignore_edid_cb, self.config_hdmi_boost_sb)
        MainDialog.setTabOrder(self.config_hdmi_boost_sb, self.overscan_gb)
        MainDialog.setTabOrder(self.overscan_gb, self.overscan_left_sb)
        MainDialog.setTabOrder(self.overscan_left_sb, self.overscan_right_sb)
        MainDialog.setTabOrder(self.overscan_right_sb, self.overscan_top_sb)
        MainDialog.setTabOrder(self.overscan_top_sb, self.overscan_bottom_sb)
        MainDialog.setTabOrder(self.overscan_bottom_sb, self.hdmi_drive_cb)
        MainDialog.setTabOrder(self.hdmi_drive_cb, self.hdmi_force_edid_audio_cb)
        MainDialog.setTabOrder(self.hdmi_force_edid_audio_cb, self.spi_cb)
        MainDialog.setTabOrder(self.spi_cb, self.i2c_cb)
        MainDialog.setTabOrder(self.i2c_cb, self.i2s_cb)
        MainDialog.setTabOrder(self.i2s_cb, self.bluetooth_cb)
        MainDialog.setTabOrder(self.bluetooth_cb, self.audio_cb)

    def retranslateUi(self, MainDialog):
        _translate = QtCore.QCoreApplication.translate
        MainDialog.setWindowTitle(_translate("MainDialog", "RPi Configuration"))
        self.graphics_driver_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Graphics driver</span></p><p>Choose which display driver you\'d like from this dropdown. The three options are:</p><ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">fkms-v3d</span>: an accelerated, GL-based graphics driver, using DispmanX for composition (\'fake\' KMS); recommended for most users (required for audio out on the Pi-Top), and the shipped default on the image;</li><li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">kms-v3d</span>: as above, but using the kernel KMS driver for composition (\'full\' KMS); may be used by non-Pi-Top users (if display manager compositing is turned off); and</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">framebuffer</span>: fallback, unaccelerated graphics driver.</li></ol><p>Please note that currently, MMAL and OpenMAX IL access to the GPU is <span style=\" font-style:italic;\">unavailable</span> when booted into a 64-bit userspace (this issue is common to all 64-bit distros for the RPi3/4, not just Gentoo). </p><p>However, as of kernels &gt;= 4.19, camera and video codec access <span style=\" font-style:italic;\">are</span> available in 64-bit mode, via v4l2.</p></body></html>"))
        self.graphics_driver_lb.setText(_translate("MainDialog", "Graphics driver:"))
        self.graphics_driver_cb.setItemText(0, _translate("MainDialog", "fkms-v3d"))
        self.graphics_driver_cb.setItemText(1, _translate("MainDialog", "kms-v3d"))
        self.graphics_driver_cb.setItemText(2, _translate("MainDialog", "framebuffer"))
        self.cma_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">CMA</span></p><p>You can set the amount of memory to allocate to the graphics driver here. CMA is a dynamic, contiguous allocator provided by the kernel.</p><p>For most users, it is recommended to set this to <span style=\" font-weight:600;\">256 MiB</span> (ensuring optimal display performance), unless you will be very short of RAM for your running applications. On modern systems this may also safely be left set to &quot;Unspecified&quot;.</p></body></html>"))
        self.cma_lb.setText(_translate("MainDialog", "CMA:"))
        self.cma_cb.setItemText(0, _translate("MainDialog", "256 MiB"))
        self.cma_cb.setItemText(1, _translate("MainDialog", "192 MiB"))
        self.cma_cb.setItemText(2, _translate("MainDialog", "128 MiB"))
        self.cma_cb.setItemText(3, _translate("MainDialog", "96 MiB"))
        self.cma_cb.setItemText(4, _translate("MainDialog", "64 MiB"))
        self.cma_cb.setItemText(5, _translate("MainDialog", "Unspecified"))
        self.gpu_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">GPU</span></p><p>You can set the amount of memory to allocate to the GPU here.</p><p>If you plan to use the RPi3/4\'s hardware video codecs (requires kernel &gt;= 4.19), then at least <span style=\" font-weight:600;\">96 MiB</span> is required.</p><p>If you plan to use the camera (requires kernel &gt;= 4.19), then at least <span style=\" font-weight:600;\">128 MiB</span> is required.</p><p>Otherwise, <span style=\" font-weight:600;\">16 MiB</span> will suffice (note that setting this low a GPU value will force <span style=\" font-style:italic;\">/boot/start_cd*.dat</span> to load).</p></body></html>"))
        self.gpu_lb.setText(_translate("MainDialog", "GPU:"))
        self.gpu_cb.setItemText(0, _translate("MainDialog", "256 MiB"))
        self.gpu_cb.setItemText(1, _translate("MainDialog", "192 MiB"))
        self.gpu_cb.setItemText(2, _translate("MainDialog", "128 MiB"))
        self.gpu_cb.setItemText(3, _translate("MainDialog", "96 MiB"))
        self.gpu_cb.setItemText(4, _translate("MainDialog", "64 MiB"))
        self.gpu_cb.setItemText(5, _translate("MainDialog", "32 MiB"))
        self.gpu_cb.setItemText(6, _translate("MainDialog", "16 MiB"))
        self.gpu_cb.setItemText(7, _translate("MainDialog", "Unspecified"))
        self.normal_mode_rb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Normal mode</span></p><p>Select this for more control over HDMI display output (recommended).</p><p>It is then also recommended to choose &quot;Auto-detect from EDID&quot; for both HDMI group and HDMI mode below, unless your monitor displays in a lower resolution than that you know it is capable of (in which case, choose an appropriate <span style=\" background-color:transparent;\">explicit</span> HDMI group, and if required, an appropriate explicit HDMI mode, from the dropdowns below).</p></body></html>"))
        self.normal_mode_rb.setText(_translate("MainDialog", "Normal mode"))
        self.normal_mode_rb.setShortcut(_translate("MainDialog", "Ctrl+R"))
        self.safe_mode_rb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">\'Safe\' mode</span></p><p>Choosing this <span style=\" font-style:italic;\">forces</span> VGA (DMT 640x480 60Hz 4:3), plus some other compatibility-related settings.</p><p>Use safe mode only as a last resort: most displays offer <span style=\" font-style:italic;\">significantly</span> higher resolution than VGA, and your RPi can select these higher resolutions automatically, if you choose Normal mode, and then &quot;Auto-detect from EDID&quot; for both HDMI group and HDMI mode from the dropdowns below.</p><p>Also note there are some fixed-resolution LCD screens that will not operate with the resolution and timing defaults of \'safe\' mode, so it is not a guaranteed lowest common denominator.</p></body></html>"))
        self.safe_mode_rb.setText(_translate("MainDialog", "\'Safe\' mode"))
        self.normal_mode_gb.setTitle(_translate("MainDialog", "Normal mode details"))
        self.hdmi_group_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">HDMI group</span></p><p>Using this dropdown, you can choose the <span style=\" font-style:italic;\">type</span> (aka, HDMI \'group\') of your attached display. For most systems, leaving this as \'auto-detect\' will work fine, but you can also explicitly choose CEA or DMT here.</p><p>CEA stands for Consumer Electronics Association, and is the standard typically used by digital TVs. DMT stands for Display Monitor Timings, and is the standard typically used by monitors.</p><p>Should you specify the CEA or DMT group explicitly, the <span style=\" font-style:italic;\">resolution, timing</span> and <span style=\" font-style:italic;\">aspect ratio</span> (aka, HDMI \'mode\') dropdown is populated by a list of settings your attached display claims to support under that group, and undimmed. Again, you can then use auto-detect, or choose a mode explicitly. Note that most modern monitors - and some modern TVs - can work in <span style=\" font-style:italic;\">either </span><span style=\" text-decoration: underline;\">group</span>, but may support different (effective) <span style=\" text-decoration: underline;\">modes</span> in each case.</p><p>Why specify the group and/or mode <span style=\" background-color:transparent;\">explicitly</span>? The most common use case is when your system boots up OK, but auto-selects a much lower resolution than you know your display is capable off. This sometimes happens because manufacturers mark a low (e.g., VGA) resolution as \'preferred\', for compatibility, in their products\' supported-mode lists. In such a case, you can use the group and mode dropdowns to choose something better.</p><p><span style=\" font-weight:600;\">NB:</span> you generally do <span style=\" font-style:italic;\">not</span> need to override the display EDID (checkbox below), even if you are using a custom HDMI group and/or mode, unless your display returns only very few valid modes for your target group (and you know it supports more).</p></body></html>"))
        self.hdmi_group_lb.setText(_translate("MainDialog", "HDMI group:"))
        self.hdmi_group_cb.setItemText(0, _translate("MainDialog", "Auto-detect from EDID"))
        self.hdmi_group_cb.setItemText(1, _translate("MainDialog", "1: CEA (some monitors, most HDMI TVs)"))
        self.hdmi_group_cb.setItemText(2, _translate("MainDialog", "2: DMT (most monitors, newer HDMI TVs)"))
        self.hdmi_mode_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">HDMI mode</span></p><p>This dropdown contains a list of resolutions, frequencies and aspect ratios (aka \'modes\') your display claims to accept for the current group. Try booting under \'auto-select\' first, and only if that result is unsuitable (very low-res, for example), and changing group doesn\'t help, proceed to setting the value manually.</p><p>NB: if you have <span style=\" font-style:italic;\">no</span> display connected to your RPi (for example, because you are using VNC), you will need to elect to override the EDID (checkbox below), to get a default list of modes presented here.</p></body></html>"))
        self.hdmi_mode_lb.setText(_translate("MainDialog", "HDMI mode:"))
        self.additional_opts_gb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Additional options</span></p><p>These options are overridden if \'safe\' mode is set.</p></body></html>"))
        self.additional_opts_gb.setTitle(_translate("MainDialog", "Additional options"))
        self.hdmi_force_hotplug_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Force HDMI output</span></p><p>When checked, pretend that the HDMI hotplug signal is asserted, so it appears that a HDMI display is attached. In other words, HDMI output mode will be used, even if no HDMI monitor is detected.</p></body></html>"))
        self.hdmi_force_hotplug_cb.setText(_translate("MainDialog", "Force HDMI output, even if no display detected"))
        self.hdmi_ignore_edid_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Override HDMI display\'s reported EDID</span></p><p>When checked, your connected display\'s reported EDID (Extended Display Identification Data) will be ignored. This can be useful if your display does not have an accurate EDID, or if you have no display currently connected.</p><p>A default (rather than display-customized) set of HDMI modes for each group may be chosen in the dropdown above, when this is selected.</p><p><span style=\" font-weight:600;\">NB</span>: most users will <span style=\" font-style:italic;\">not</span> need to select this option, even when using a custom HDMI group and mode.</p></body></html>"))
        self.hdmi_ignore_edid_cb.setText(_translate("MainDialog", "Override HDMI display\'s reported EDID data (if any)"))
        self.config_hdmi_boost_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">HDMI output signal level</span></p><p>Configures the signal strength of the HDMI interface. The default value is 5.</p><p>If you are seeing HDMI issues (speckling, interference) then try 7. Very long HDMI cables may need up to 11, but values this high should not be used unless absolutely necessary.</p></body></html>"))
        self.config_hdmi_boost_lb.setText(_translate("MainDialog", "HDMI output signal level:"))
        self.overscan_gb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overscan Correction</span></p><p>If your desktop appears \'clipped\' by the edges of the display, you can enable overscan correction, and then choose how many pixels to skip at each edge.</p><p>Most modern HDMI TVs, and nearly all monitors, will <span style=\" font-style:italic;\">not</span> require overscan enabled. The issue mostly occurs with older HDMI TVs.</p></body></html>"))
        self.overscan_gb.setTitle(_translate("MainDialog", "Overscan"))
        self.overscan_left_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overscan left</span></p><p>Specifies the number of pixels to skip on the left edge of the screen, when overscan is enabled.</p><p>Increase this value if your desktop flows off the left edge of the screen; decrease it if there is a black border between the left edge of the screen and the desktop.</p></body></html>"))
        self.overscan_left_lb.setText(_translate("MainDialog", "Left:"))
        self.overscan_right_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overscan right</span></p><p>Specifies the number of pixels to skip on the right edge of the screen, when overscan is enabled.</p><p>Increase this value if your desktop flows off the right edge of the screen; decrease it if there is a black border between the right edge of the screen and the desktop.</p></body></html>"))
        self.overscan_right_lb.setText(_translate("MainDialog", "Right:"))
        self.overscan_top_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overscan top</span></p><p>Specifies the number of pixels to skip on the top edge of the screen, when overscan is enabled.</p><p>Increase this value if your desktop flows off the top edge of the screen; decrease it if there is a black border between the top edge of the screen and the desktop.</p></body></html>"))
        self.overscan_top_lb.setText(_translate("MainDialog", "Top:"))
        self.overscan_bottom_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overscan bottom</span></p><p>Specifies the number of pixels to skip on the bottom edge of the screen, when overscan is enabled.</p><p>Increase this value if your desktop flows off the bottom edge of the screen; decrease it if there is a black border between the bottom edge of the screen and the text.</p></body></html>"))
        self.overscan_bottom_lb.setText(_translate("MainDialog", "Bottom:"))
        self.further_settings_gb.setTitle(_translate("MainDialog", "Further display settings"))
        self.hdmi_drive_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Force audio output in DMT modes</span></p><p>Selecting this forces normal HDMI sound output, rather than DVI. It can make sound playback work when connected to a monitor (or an HDMI TV that appears, through its EDID, to be a monitor), provided the device incorporates a speaker, of course.</p></body></html>"))
        self.hdmi_drive_cb.setText(_translate("MainDialog", "Force audio output in DMT modes"))
        self.hdmi_force_edid_audio_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Assume display supports audio</span></p><p>When checked, it will be assumed that your display supports <span style=\" font-style:italic;\">all</span> audio formats (regardless of what its EDID says). This allows passthrough of DTS/AC3 even when this is not reported as supported.</p><p>Most users will not need to select this, but it can be useful to make audio output work for certain displays.</p></body></html>"))
        self.hdmi_force_edid_audio_cb.setText(_translate("MainDialog", "Assume display supports audio (partial EDID override)"))
        self.pi4_display_gb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Pi4 display settings</span></p><p>These settings only apply to the RPi4, and have no effect when booted on an RPi3.</p></body></html>"))
        self.pi4_display_gb.setTitle(_translate("MainDialog", "Pi4 display settings"))
        self.pi4_4kp60_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Enable 4Kp60 output on HDMI0</span></p><p>By default, when connected to a 4K monitor, the RPi4B will select a 30Hz refresh rate. Check this box to enable use of a 60Hz refresh rate on HDMI0.</p><p>Note that this will increase both the power consumption and running temperature of the RPi4. It is not possible to output 4Kp60 on both HDMI ports simultaneously.</p><p>This option has no effect on an RPi3.</p></body></html>"))
        self.pi4_4kp60_cb.setText(_translate("MainDialog", "Enable 4Kp60 output on HDMI0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.display_tab), _translate("MainDialog", "Display"))
        self.hdmi1_gb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">RPi4 only (HDMI1 port)</span></p><p>These settings affect the <span style=\" font-style:italic;\">second</span> HDMI port - this connector is only present on the RPi4, and is the one <span style=\" font-style:italic;\">further</span> from the USB-C power connector (the other being HDMI0, the default).</p><p>They have no effect on an RPi3, nor on an RPi4 which has no display connected to the HDMI1 port.</p></body></html>"))
        self.hdmi1_gb.setTitle(_translate("MainDialog", "RPi4 only (HDMI1 port)"))
        self.normal_mode1_rb.setText(_translate("MainDialog", "Normal mode"))
        self.safe_mode1_rb.setText(_translate("MainDialog", "\'Safe\' mode"))
        self.normal_mode1_gb.setTitle(_translate("MainDialog", "Normal mode details"))
        self.hdmi_group1_cb.setItemText(0, _translate("MainDialog", "Auto-detect from EDID"))
        self.hdmi_group1_cb.setItemText(1, _translate("MainDialog", "1: CEA (some monitors, most HDMI TVs)"))
        self.hdmi_group1_cb.setItemText(2, _translate("MainDialog", "2: DMT (most monitors, newer HDMI TVs"))
        self.hdmi_mode1_lb.setText(_translate("MainDialog", "HDMI mode:"))
        self.hdmi_group1_lb.setText(_translate("MainDialog", "HDMI group:"))
        self.additional_opts1_gb.setTitle(_translate("MainDialog", "Addititional optiions"))
        self.hdmi_force_hotplug1_cb.setText(_translate("MainDialog", "Force HDMI output, even if no display detected"))
        self.hdmi_ignore_edid1_cb.setText(_translate("MainDialog", "Override HDMI display\'s reported EDID data (if any)"))
        self.config_hdmi_boost1_lb.setText(_translate("MainDialog", "HDMI output signal level:"))
        self.overscan1_gb.setTitle(_translate("MainDialog", "Overscan"))
        self.overscan_left1_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overscan left</span></p><p>Specifies the number of pixels to skip on the left edge of the screen, when overscan is enabled.</p><p>Increase this value if your desktop flows off the left edge of the screen; decrease it if there is a black border between the left edge of the screen and the desktop.</p></body></html>"))
        self.overscan_left1_lb.setText(_translate("MainDialog", "Left:"))
        self.overscan_right1_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overscan right</span></p><p>Specifies the number of pixels to skip on the right edge of the screen, when overscan is enabled.</p><p>Increase this value if your desktop flows off the right edge of the screen; decrease it if there is a black border between the right edge of the screen and the desktop.</p></body></html>"))
        self.overscan_right1_lb.setText(_translate("MainDialog", "Right:"))
        self.overscan_top1_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overscan top</span></p><p>Specifies the number of pixels to skip on the top edge of the screen, when overscan is enabled.</p><p>Increase this value if your desktop flows off the top edge of the screen; decrease it if there is a black border between the top edge of the screen and the desktop.</p></body></html>"))
        self.overscan_top1_lb.setText(_translate("MainDialog", "Top:"))
        self.overscan_bottom1_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overscan bottom</span></p><p>Specifies the number of pixels to skip on the bottom edge of the screen, when overscan is enabled.</p><p>Increase this value if your desktop flows off the bottom edge of the screen; decrease it if there is a black border between the bottom edge of the screen and the text.</p></body></html>"))
        self.overscan_bottom1_lb.setText(_translate("MainDialog", "Bottom:"))
        self.further_settings2_gb.setTitle(_translate("MainDialog", "Further settings"))
        self.hdmi_drive1_cb.setText(_translate("MainDialog", "Force audio output in DMT modes"))
        self.hdmi_force_edid_audio1_cb.setText(_translate("MainDialog", "Assume display supports audio (partial EDID override)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.second_display_tab), _translate("MainDialog", "Second Display"))
        self.main_interfaces_gb.setTitle(_translate("MainDialog", "Main interfaces"))
        self.spi_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Enable SPI</span></p><p>When checked, the RPi\'s SPI (Serial Peripheral Interface) will be enabled.</p></body></html>"))
        self.spi_cb.setText(_translate("MainDialog", "Enable SPI"))
        self.i2c_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Enable I</span><span style=\" font-weight:600; vertical-align:super;\">2</span><span style=\" font-weight:600;\">C</span></p><p>When checked, the RPi\'s I<span style=\" vertical-align:super;\">2</span>C (Inter-Integrated Circuit, pronounced eye-squared-see) interface will be enabled.</p><p>Despite the similar name, it is unrelated to the I<span style=\" vertical-align:super;\">2</span>S interface, below.</p></body></html>"))
        self.i2c_cb.setText(_translate("MainDialog", "Enable I2C"))
        self.i2s_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Enable I</span><span style=\" font-weight:600; vertical-align:super;\">2</span><span style=\" font-weight:600;\">S</span></p><p>When checked, the RPi\'s I<span style=\" vertical-align:super;\">2</span>S (Inter-IC Sound, pronounced eye-squared-ess) interface will be enabled.</p><p>Despite the similar name, it is unrelated to the I<span style=\" vertical-align:super;\">2</span>C interface, above.</p></body></html>"))
        self.i2s_cb.setText(_translate("MainDialog", "Enable I2S"))
        self.bluetooth_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Enable Bluetooth</span></p><p>When checked, the RPi\'s inbuilt Bluetooth will be enabled. When unchecked, UART0/ttyAMA0 over GPIOs 14 &amp; 15 becomes usable instead.</p><p><span style=\" font-weight:600;\">NB</span>: if do <span style=\" font-style:italic;\">not</span> wish to use Bluetooth, remember to also disable the OpenRC service that initialises the modem, so it doesn\'t utilize the UART. To do so, issue:<br/><span style=\" font-family:\'monospace\';\">sudo rc-service rpi3-bluetooth stop</span><br/>followed by:<br/><span style=\" font-family:\'monospace\';\">sudo rc-update del rpi3-bluetooth default</span></p></body></html>"))
        self.bluetooth_cb.setText(_translate("MainDialog", "Enable Bluetooth (disables serial port)"))
        self.audio_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Enable audio</span></p><p>When checked, the RPi\'s onboard ALSA interface will be enabled.</p></body></html>"))
        self.audio_cb.setText(_translate("MainDialog", "Enable audio"))
        self.camera_cb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Enable camera</span></p><p>When checked, the RPi\'s onboard camera interface will be enabled. Requires kernel &gt;=4.19 to operate.</p><p>You must allocate at least 128 MiB of GPU memory when using the camera.</p></body></html>"))
        self.camera_cb.setText(_translate("MainDialog", "Enable camera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wifi_tab), _translate("MainDialog", "Interfaces"))
        self.wifi_setup_gb.setTitle(_translate("MainDialog", "WiFi settings"))
        self.wifi_country_code_lb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Regulatory domain</span></p><p>Using this dropdown, you can select the appropriate WiFi regulatory domain.</p><p>This enables the use of WiFi channels (frequencies) and power levels appropriate to your country.</p></body></html>"))
        self.wifi_country_code_lb.setText(_translate("MainDialog", "Regulatory domain:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainDialog", "WiFi"))
        self.overclocking_gb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Overclocking</span></p><p>It is possible to <span style=\" font-style:italic;\">overclock</span> the Pi4 without voiding your warranty. On the image as shipped, no overclocking is set, but you can use these radio buttons to select a more aggressive profile. Overclocking generally means that applications will run more quickly (although this will vary from case to case). The settings below have no effect on a Pi3.</p><p>There is a risk that your system will fail to boot, or exhibit instability once booted, at the faster profiles - if so, just comment out the arm<span style=\" font-style:italic;\">_freq</span> and <span style=\" font-style:italic;\">gpu_freq</span> settings in <span style=\" font-style:italic;\">/boot/config.txt</span>, and try again.</p><p>Most Pi4s should boot fine with the &quot;Mild&quot; or &quot;Mid&quot; overclocking settings. Your system will use more power, and run hotter with overclocking in use, so an official power supply, and possibly some active cooling, may be necessary to fully exploit the increased performance (since the system will automatically \'throttle\' to prevent damage should the temperature get too high).</p><p>For avoidance of doubt, none of the below settings set<span style=\" font-style:italic;\"> force_turbo=1</span>, nor do they set an <span style=\" font-style:italic;\">over_voltage&gt;6</span> (&gt; +0.15V), so per current RPF advice should not affect your warranty.</p><p><span style=\" font-weight:600;\">NB: </span><span style=\" font-style:italic;\">the above notwithstanding, use settings higher than &quot;None&quot; at your own risk!</span></p></body></html>"))
        self.overclocking_gb.setTitle(_translate("MainDialog", "Overclocking"))
        self.overclock0_rb.setText(_translate("MainDialog", "None (1500MHz CPU, 500MHz GPU, +0.00V)"))
        self.overclock1_rb.setText(_translate("MainDialog", "Mild (1750MHz CPU, 500MHz GPU, +0.05V)"))
        self.overclock2_rb.setText(_translate("MainDialog", "Mid (1750MHz CPU, 600MHz GPU, +0.10V)"))
        self.overclock3_rb.setText(_translate("MainDialog", "Extreme (2000MHz CPU, 600MHz GPU, +0.15V)"))
        self.overclock4_rb.setText(_translate("MainDialog", "Custom (Settings in config.txt not overridden)"))
        self.pimoroni_gb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Pimoroni Fan SHIM</span></p><p>The RPi4 can run somewhat hot under heavy load, and in the absence of active cooling, the CPU will throttle back automatically at 80°C, lowering its performance to stay within a safe thermal operating range.</p><p>One popular third-party add-on to counter this effect is the Fan SHIM from Pimoroni. This clips onto the GPIO header, without soldering.</p><p>If you have one of these daughterboards fitted to your RPi4, click this checkbox to activate it, and use the slider to set the SoC temperature at which the fan will spin up. The driver has a built-in hysteresis, which will automatically turn the fan off again at 10°C below this setpoint.</p><p>These settings have no effect if booted on an RPi3.</p></body></html>"))
        self.pimoroni_gb.setTitle(_translate("MainDialog", "Pimoroni Fan SHIM"))
        self.start_fan_lb.setText(_translate("MainDialog", "Start fan at:"))
        self.fan_temps_lb.setText(_translate("MainDialog", "65°C (off at 55°C)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainDialog", "Pi4 Tuning"))
        self.layout_editor_pb.setToolTip(_translate("MainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Launch Screen Layout Editor</span></p><p>This button starts the <span style=\" font-weight:600;\">arandr</span> program, which you can use to specify how your (possibly dual-monitor) display is laid out (horizontally stacked, vertically stacked, rotated <span style=\" font-style:italic;\">etc</span>.).</p><p>You can <span style=\" font-weight:600;\">save</span> your changes within the arandr program to a script file. If you do so to the location <span style=\" font-style:italic;\">~/.screenlayout/default.sh</span>, they will automatically be applied for you each login.</p><p>The arandr program can also be started via the menu (it lives at <span style=\" font-family:\'monospace\';\">Applications</span> → <span style=\" font-family:\'monospace\';\">Settings</span> → <span style=\" font-family:\'monospace\';\">ARandR</span>).</p></body></html>"))
        self.layout_editor_pb.setText(_translate("MainDialog", "Launch Screen Layout Editor"))
from pyconfig_gen import pyconfig_gen_rc
